spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: create-drop
    defer-datasource-initialization: true
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:DATABASE
    driver-class-name: org.h2.Driver
    username: sa
    password:

jwt:
  secret-key: SecretKeyForMong2SecretKeyForMong2
  expire-length: 36000000

sendgrid:
  authentication: Bearer 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
  timeout:
    connect: 3
    read: 10
  url:
    base: https://api.sendgrid.com/v3
    send: /mail/send
  render:
    from: wodnd0131@naver.com

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

