spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: create-drop
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:DATABASE
    driver-class-name: org.h2.Driver
    username: sa
    password:

jwt:
  secret: SecretKeyForMong2

sendgrid:
  authentication: Bearer SG.G9XLDCsNQAWM9AvrTJ5Rsw.NajanIBQ4ELJTEOI4GnrEu6WrL5tWoOlLAEoTONAftg
  timeout:
    connect: 3
    read: 10
  url:
    base: https://api.sendgrid.com/v3
    send: /mail/send
  render:
    from: wodnd0131@mju.ac.kr

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

